[server]
enableStaticServing = true

[theme]
# Uncomment and edit any line below to customize your app's appearance
base="dark"
primaryColor="#3A7CA5"
backgroundColor="#0F1720"
secondaryBackgroundColor="#1A2430"
textColor="#E6EDF3"
font="sans serif"
